name: icare
description: A Nursing Student Learning App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_database: ^9.0.10
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  get: ^4.6.1
  http: ^0.13.4
  buttons_tabbar: ^1.3.4
  video_thumbnail: ^0.5.0
  webview_flutter: ^3.0.2
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
    - family: GoogleSansBold
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf